### ISSUE TITLE
Handling horizontal rules

### ISSUE THREAD

**Issue by apepindev** [buzzylab/laradown#12]
In [line 35 on the Laradown.php](https://github.com/buzzylab/laradown/blob/master/src/Laradown.php#L35), it's checking if the element name starts with 'h'. This breaks in the next line when the name is 'hr' for horizontal rules as the text index doesn't exist.

**Comment by maherelgamil** [comment]
@Paradiddley thanks you for reporting this issue, and I am sorry for being late.
I review your [pull request](https://github.com/buzzylab/laradown/pull/10) and I merged it.

Thanks again.

**Comment by apepindev** [comment]
Not a problem, and thank you. 

Also, user 'greut' should take the credit for the pull request!

**Comment by maherelgamil** [comment]
All pull requests merged.
